---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shahryartyabe/simplesocial.shahryartayeb.com
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/css